###############################################################################
# sTiles Memory Module
###############################################################################

STILES_DIR := ../..
SRC := memory_stub.cpp memory_api.cpp

include $(STILES_DIR)/tools/module.mk
