###############################################################################
# sTiles Free Module — TiledMatrix / scheme cleanup routines
###############################################################################

STILES_DIR := ../..
SRC := free.cpp

include $(STILES_DIR)/tools/module.mk
