###############################################################################
# sTiles Control Module
###############################################################################

STILES_DIR := ../..
SRC := allocate.cpp context.cpp control.cpp stilesos.cpp stiles_threadsetting.cpp

include $(STILES_DIR)/tools/module.mk
