###############################################################################
# sTiles DenseTile Module (Core BLAS)
# Objects are included in libstiles.a (no separate libcoreblas)
###############################################################################

STILES_DIR := ../..
SRC := core_kernels.cpp
EXTRA_INC := -I../common -I../control

include $(STILES_DIR)/tools/module.mk
