###############################################################################
# sTiles Symbolic Module
###############################################################################

STILES_DIR := ../..
SRC := dpotrf_symbolic.cpp pdpotrf_symbolic.cpp
EXTRA_INC := -I../control

include $(STILES_DIR)/tools/module.mk
